# put in path ~/.dbt/profiles.yml

company: #this needs to match your profile in your project.yml
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: big-time-data-project #bigquery project name
      dataset: dbt_rachel #this will be where your locally ran models will show up
      threads: 4